test: annotations changes

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -123,13 +123,8 @@ jobs:
           set -uo pipefail
           set +e
           set -x
-          
-          #terraform plan -out=tfplan -detailed-exitcode 
-          #terraform plan -input=false -no-color -out=tfplan 2>&1 | tee plan.out
-          
-          #terraform plan -input=false -detailed-exitcode -out=tfplan 2>&1 | tee plan.out
 
-          terraform plan -input=false -detailed-exitcode -out=tfplan > >(tee /dev/tty) 2> >(tee plan.out >&2)
+          terraform plan -input=false -detailed-exitcode -no-color -out=tfplan > >(tee /dev/tty) 2> >(tee plan.out >&2)
           EXIT_CODE=$?
           set -e
 
@@ -154,7 +149,32 @@ jobs:
       - name: Terraform apply
         run: |
           cd "${{ inputs.test_type }}"
-          #terraform apply -auto-approve tfplan
+          
+          set -uo pipefail
+          set +e
+          set -x
+
+          #terraform apply -input=false -auto-approve -no-color tfplan > >(tee /dev/tty) 2> >(tee apply.out >&2)
+          EXIT_CODE=$?
+          set -e
+
+          if [ "$EXIT_CODE" -ne 0 ]; then
+            echo "::error title=Terraform Plan Failed::Check summary for details"
+            
+            echo "## ❌ Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "**Module:**  ${{ inputs.test_type }} " >> $GITHUB_STEP_SUMMARY
+            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
+            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY
+
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            tail -n 50 apply.out >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+
+            exit 1
+          fi
 
       - name: Wait
         run: sleep 60
@@ -162,4 +182,28 @@ jobs:
       - name: Terraform destroy
         run: |
           cd "${{ inputs.test_type }}"
+          set -uo pipefail
+          set +e
+          set -x
+
+          #terraform destroy -input=false -auto-approve -no-color > >(tee /dev/tty) 2> >(tee destroy.out >&2)          EXIT_CODE=$?
+          set -e
+
+          if [ "$EXIT_CODE" -ne 0 ]; then
+            echo "::error title=Terraform Plan Failed::Check summary for details"
+            
+            echo "## ❌ Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "**Module:**  ${{ inputs.test_type }} " >> $GITHUB_STEP_SUMMARY
+            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
+            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY
+
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            tail -n 50 apply.out >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+
+            exit 1
+          fi
           #terraform destroy -auto-approve
